package com.gds.calendar;

/**
 * @author Matt Vickery (matt.d.vickery@greendotsoftware.co.uk)
 * @since 21/08/2017
 *
 * Events generated by the LocalDateCalendar.
 */
public enum CalendarChangeEvent {

    INITIALISED,
    DATE_ADDED,
    DATE_REMOVED,
    DATES_REMOVED,
    CALENDAR_ADDED,
    CALENDAR_REMOVED,
    WEEKDAY_REMOVED
}